### ISSUE TITLE
Additional RSVP imports

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-rfc176-data#13]
Right now it is only possible to

```js
import RSVP from 'rsvp';
```

but to get to `Promise` or `resolve()` it is not possible to

```js
import { Promise, resolve } from 'rsvp';
```

IMHO we should change that

**Comment by locks** [comment]
Not a bad idea, indeed.

**Comment by rwjblue** [comment]
Seems like a dupe of https://github.com/ember-cli/ember-cli-shims/pull/67 which @stefanpenner opposed :confused:

**Comment by cibernox** [comment]
FWIW, I think that it makes sense to expose `Promise` directly, without destructuring RSVP. However, since `Promise.resolve` is part of the spec, I don't see the case for `RSVP.resolve`, unless there is some subtle difference I'm not aware of.

**Comment by rwjblue** [comment]
Some of this is done, but as I mentioned in #18 we should likely bring in a few more named exports here.
