### ISSUE TITLE
Ember.deprecate transformation seems to be missing

### ISSUE THREAD

**Issue by abhilashlr** [ember-cli/ember-rfc176-data#203]
Ran a codemod on this file: https://github.com/abhilashlr/ember-cli-flash/blob/master/app/initializers/flash-messages.js

Line 4 did not transform well to `import { deprecate } from "@ember/application/deprecations"` as mentionned in https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md

**Comment by rwjblue** [comment]
importing it from `@ember/application/deprecations` is itself deprecated, the documentation should now state that it comes from `@ember/debug`.

**Comment by rwjblue** [comment]
I think this is resolved now, closing...
