### ISSUE TITLE
Unknown global Ember.inject

### ISSUE THREAD

**Issue by Dhaulagiri** [ember-cli/ember-rfc176-data#34]
If you have inject destructured like this the ember-modules-codemod fails stating this in an unkown global:

`const { inject } = Ember;`

This form of destructing does work:

`const { inject: { service } } = Ember;`

Can/should the first case be supported?

**Comment by rwjblue** [comment]
Firstly, I think that this is _probably_ a `ember-modules-codemod` issue (this repo is just where we house the shared data between ember-modules-codemod and babel-plugin-ember-modules-api-polyfill packages).

Secondly, I do think that the codemod could be updated to be aware of this. FWIW, I suspect is also an issue for folks using `Ember.computed` like this:

```js
import Ember from 'ember';

const { computed } = Ember;

// ...snip...

  foo: computed.alias('whatever.foo'),
```

**Comment by Dhaulagiri** [comment]
I was a little confused about which repo to open on.  I'll close this and move over.

FWIW at a cursory glance the codemod _does_ seem to handle the Ember.computed scenario you have here correctly.
