### ISSUE TITLE
How I can get Ember.NAME_KEY ?

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-rfc176-data#47]

**Comment by Turbo87** [comment]
```
import Ember from 'ember';

doStuffWith(Ember.NAME_KEY);
```

`NAME_KEY` does not have an ES6 modules export because it will likely be removed in the future once there is a suitable replacement. How that will look like is unknown though so for now you should keep using `Ember.NAME_KEY` if you need it.

**Comment by rwjblue** [comment]
TBH, you shouldn’t really need (or use) `Ember.NAME_KEY` anyways. In nearly all cases customizing your objects `toString` method is better and more idiomatic...
