### ISSUE TITLE
Namespace import

### ISSUE THREAD

**Issue by thec0keman** [ember-cli/ember-rfc176-data#59]
`import Namespace from '@ember/application/namespace';` is [listed](https://github.com/ember-cli/ember-rfc176-data#emberapplication), however I am getting a `module not found` error.

This is on:
ember-cli: 3.3.0
ember-source: 3.3.0

I'm not sure if it is best to report this here or in the main Ember repo, but is this currently available / behind some kind of special flag?

Thanks!

**Comment by rondale-sc** [comment]
I'm running into this as well.  Though it appears the mapping is present in this repo:

https://github.com/ember-cli/ember-rfc176-data/blob/master/mappings.json#L59

**Comment by rwjblue** [comment]
`Ember.Namespace` was added a couple months ago in https://github.com/ember-cli/ember-rfc176-data/pull/48, which was released as v0.3.3.

Can y'all check `npm ls ember-rfc176-data` to see what versions are in use?

**Comment by thec0keman** [comment]
Thanks @rwjblue  that's helpful.  I think the issue is we are still using `ember-cli-shims` since we have a number of addons that are on an older version of `ember-cli-babe`.
